abstract class CounterStat{}
class CategoryLoadingStat extends CounterStat{}
class CategorySucessStat extends CounterStat{}
class CategoryErrorStat extends CounterStat{}
class ProductOfCategoryLoadingStat extends CounterStat{}
class ProductOfCategorySucessStat extends CounterStat{}
class ProductOfCategoryErrorStat extends CounterStat{}
class GetNewProductLoadingStat extends CounterStat{}
class GetNewProductSucessStat extends CounterStat{}
class GetNewProductErrorStat extends CounterStat{}
class UpdateProductLoadingStat extends CounterStat{}
class UpdateProductSucessStat extends CounterStat{}
class UpdateProductErrorStat extends CounterStat{}
class ShowProductLoadingStat extends CounterStat{}
class ShowProductSucessStat extends CounterStat{}
class ShowProductErrorStat extends CounterStat{}
class GetProductLoadingStat extends CounterStat{}
class GetProductSucessStat extends CounterStat{}
class GetProductErrorStat extends CounterStat{}
class SearchProductLoadingStat extends CounterStat{}
class SearchProductSucessStat extends CounterStat{}
class SearchProductErrorStat extends CounterStat{}
